<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Understanding ECMAScript 6</name>
   <tag></tag>
   <elementGuidId>4323bd75-81e7-4542-8a30-f42eb085c36d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//label[@id='userName-value'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#title-wrapper > div.col-md-9.col-sm-12 > #userName-value</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>be4e8d98-729d-467d-8a1e-c03f203f64f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-label</value>
      <webElementGuid>e29ca094-b254-4d8a-b534-df06f4034a7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>color</name>
      <type>Main</type>
      <value>#000000</value>
      <webElementGuid>ed2be6fb-a91c-4d8f-8693-2d8733a80a76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>userName-value</value>
      <webElementGuid>dc2f02d5-06c3-4c5e-89a9-6da281e4bcad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Understanding ECMAScript 6</value>
      <webElementGuid>95271293-9b6f-4e0c-8dc0-1bccfa45f616</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;title-wrapper&quot;)/div[@class=&quot;col-md-9 col-sm-12&quot;]/label[@id=&quot;userName-value&quot;]</value>
      <webElementGuid>8edd102d-90f7-49fe-ab76-923c11f29dd5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//label[@id='userName-value'])[2]</value>
      <webElementGuid>e4169647-50b6-433c-9a58-17a9950fe174</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='title-wrapper']/div[2]/label</value>
      <webElementGuid>90756b3f-cc5e-4c4c-be25-c429f80ac7a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/label</value>
      <webElementGuid>e13e128b-f03d-4552-9a28-eb15f0b15ebd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'userName-value' and (text() = 'Understanding ECMAScript 6' or . = 'Understanding ECMAScript 6')]</value>
      <webElementGuid>ce48c0d8-f19b-4ed5-9d41-3f692d417734</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
