<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div</name>
   <tag></tag>
   <elementGuidId>0aa1289d-35c9-444b-87ef-56b8bc9530bb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='fixedban']/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#fixedban > div > div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5424aab7-5083-4199-9f4c-da31fe1609aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fixedban&quot;)/div[1]/div[1]</value>
      <webElementGuid>5c109dbd-619a-439d-9ec7-31c7a15a5d2f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fixedban']/div/div</value>
      <webElementGuid>d3511a31-01d0-49b3-b599-94e1f9f300cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div</value>
      <webElementGuid>3071272f-3e5d-4cb9-8b24-4e8188ecdd23</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
