<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>divframe1Wrapper</name>
   <tag></tag>
   <elementGuidId>2b267ef8-877d-44b1-a7e2-26f0b50a5997</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[2]/div/div/div[2]/div[1]/div/div/div[3]/div/ul/li[3]/span
</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#frame1Wrapper</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>490ed664-3098-4be5-9e07-c5490c21c8d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frame1Wrapper</value>
      <webElementGuid>9ff543e2-637c-4490-8adb-801a3b36bb7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frame1Wrapper&quot;)</value>
      <webElementGuid>b9450fa1-9c19-48d9-8676-22a71dff46ab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frame1Wrapper']</value>
      <webElementGuid>a4c82659-bf81-4513-987a-02b4319eadb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='framesWrapper']/div[2]</value>
      <webElementGuid>597352b5-be80-4ff6-8790-ad26afbcf81d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]/div[2]</value>
      <webElementGuid>8c05e42a-6d13-4453-8090-f87720d65aaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frame1Wrapper']</value>
      <webElementGuid>942a98d8-14eb-43bc-9cd9-a78e7d229dc4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
